# Voorbeeld runlist voor demo/CI. Pas de paden aan jouw situatie aan.
runs:
  - object: M140
    variant: BNKA
    # input: data/raw/bank_raw.xlsx   # of rely on meta.sources
    report: true
    reports: [raw, validation]
    sample: 50
