name: CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONIOENCODING: utf-8
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install (editable)
        run: python -m pip install -e . --no-build-isolation

      - name: Lint configs (strict)
        run: myd-transform --lint-all --strict

      - name: Run runlist (if present) in CI mode
        if: hashFiles('config/runlist_ci.yaml') != ''
        run: myd-transform --runlist config/runlist_ci.yaml --ci

      - name: Upload reports & outputs (if they exist)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: myd-artifacts
          if-no-files-found: ignore
          path: |
            logs/**
            data/out/**
            data/rejects/**
